# Site wide configuration

title:            PC
locale:           en_GB
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: P&aacute;id&iacute; Creed
  avatar: paidi.jpg
  bio: "Engineer, mathematician, scientist, vegan."
  email: 
  disqus-shortname: paidicreed
  twitter: paidicreed
  google:
    plus: #paidicreed
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: #
  github: paidi
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: paidicreed
  xing: #username
  instagram: #paidicreed
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
